$connStr = "Server=192.168.2.34;Database=STUDIO_FISCAL;Integrated Security=True;TrustServerCertificate=True;"
$alterSql = @"
ALTER VIEW [dbo].[vw_powerbi_job_repasse]
AS

WITH Qbert AS (
    SELECT
        A.JOB,
        CAST(A.PERCENTUAL AS FLOAT) AS PERC_HONORARIOS_JOB,
        CAST(A.PERCENTUAL AS FLOAT) AS PERC_HONORARIOS_FRANQUEADO,
        CAST(A.CODIGO_UNIDADE AS BIGINT) AS UNIDADE_ID,
        U.UniEmail AS UNIDADE_EMAIL,
        CAST('' AS VARCHAR(50)) AS CNPJ_UNIDADE,
        CAST(0 AS BIGINT) AS TIPO_FRANQUIA_CODIGO,
        CAST(TF.SutfNome AS VARCHAR(100)) AS TIPO_FRANQUIA_NOME,
        CAST(A.CODIGO_CLIENTE AS BIGINT) AS PARTICIPANTE_ID,
        CAST(PCli.ParRazao AS VARCHAR(250)) AS PARTICIPANTE_RAZAO_SOCIAL,
        CAST(PCli.ParContatoNome AS VARCHAR(250)) AS PARTICIPANTE_CONTATO_NOME,
        CAST(A.PERCENTUAL AS FLOAT) AS PERC_FRANQUEADO,
        A.DATA_CADASTRO,
        CAST(PCli.ParCNPJ AS VARCHAR(50)) AS PARTICIPANTE_CPF,
        CAST(U.UniNome AS VARCHAR(250)) AS UNIDADE_NOME,
        CASE WHEN A.COBRANCA_GROSSUP = 1 THEN 'N' ELSE 'S' END AS COBRANCA_GROSSUP,
        CAST(A.CODIGO AS BIGINT) AS CODIGO,
        CASE
            WHEN ISNULL(U.UniRetemImposto, 0) = 1 THEN CAST(0.00 AS FLOAT)
            WHEN A.COBRANCA_GROSSUP = 1 AND A.DATA_CADASTRO > '20260301' THEN CAST(19.53 AS FLOAT)
            ELSE CAST(0.00 AS FLOAT)
        END AS RETENCAO,
        CASE WHEN U.UniRetemImposto = 1 THEN 'N' ELSE 'S' END AS UNIRETEMIMPOSTO,
        CAST(PCli.ParRazao AS VARCHAR(250)) AS PARTICIPANTE_CLIENTE,
        CAST(PFranq.ParRazao AS VARCHAR(250)) AS PARTICIPANTE_FRANQUEADO,
        CAST(RD.SurdNome AS VARCHAR(250)) AS REDE_DISTRIBUICAO,
        CAST(TF.SutfNome AS VARCHAR(250)) AS REDE_DISTRIBUICAO_OLD
    FROM PROJECT_QBERT_JOBS A WITH (NOLOCK)
    LEFT JOIN SMART_UNIDADES U WITH (NOLOCK) ON U.UniCodigo = A.CODIGO_UNIDADE
    LEFT JOIN SMART_PARTICIPANTES PCli WITH (NOLOCK) ON PCli.ParCodigo = A.CODIGO_CLIENTE
    LEFT JOIN SMART_PARTICIPANTES PFranq WITH (NOLOCK) ON PFranq.ParCodigo = A.CODIGO_FRANQUEADO
    OUTER APPLY (
        SELECT TOP 1 ModRedeDistribuicao, ModTipoFranquia 
        FROM SMART_UNIDADES_MODELOS WITH (NOLOCK)
        WHERE ModUnidade = A.CODIGO_UNIDADE
        ORDER BY ModAtivo DESC, ModData DESC
    ) M
    LEFT JOIN SMART_UNIDADES_REDE_DISTRIBUICAO RD WITH (NOLOCK) ON RD.SurdCodigo = M.ModRedeDistribuicao
    LEFT JOIN SMART_UNIDADES_TIPO_FRANQUIA TF WITH (NOLOCK) ON TF.SutfCodigo = M.ModTipoFranquia
    WHERE A.JOB IS NOT NULL
),
CP AS (
    SELECT
        CAST(C.CctCodigo AS VARCHAR(50)) AS JOB,
        H.HonorarioCalc AS PERC_HONORARIOS_JOB,
        H.HonorarioCalc AS PERC_HONORARIOS_FRANQUEADO,
        CAST(ISNULL(C.CctUnidadeFranqCom, ISNULL(C.CctUnidadeFranqOp, 2153)) AS BIGINT) AS UNIDADE_ID,
        UCom.UniEmail AS UNIDADE_EMAIL,
        CAST('' AS VARCHAR(50)) AS CNPJ_UNIDADE,
        CAST(0 AS BIGINT) AS TIPO_FRANQUIA_CODIGO,
        CAST('' AS VARCHAR(100)) AS TIPO_FRANQUIA_NOME,
        CAST(C.CctCliente AS BIGINT) AS PARTICIPANTE_ID,
        CAST(PCli.ParRazao AS VARCHAR(250)) AS PARTICIPANTE_RAZAO_SOCIAL,
        CAST(PCli.ParContatoNome AS VARCHAR(250)) AS PARTICIPANTE_CONTATO_NOME,
        H.HonorarioCalc AS PERC_FRANQUEADO,
        C.CctDataCadastro AS DATA_CADASTRO,
        CAST(PCli.ParCNPJ AS VARCHAR(50)) AS PARTICIPANTE_CPF,
        CAST(ISNULL(UCom.UniNome, 'STUDIO CONTABILIDADE LTDA - PILOTO') AS VARCHAR(250)) AS UNIDADE_NOME,
        'N' AS COBRANCA_GROSSUP,
        CAST(C.CctCodigo AS BIGINT) AS CODIGO,
        CAST(0.00 AS FLOAT) AS RETENCAO,
        CASE WHEN ISNULL(UCom.UniRetemImposto, 0) = 1 THEN 'N' ELSE 'S' END AS UNIRETEMIMPOSTO,
        CAST(PCli.ParRazao AS VARCHAR(250)) AS PARTICIPANTE_CLIENTE,
        CAST(PFranq.ParRazao AS VARCHAR(250)) AS PARTICIPANTE_FRANQUEADO,
        CAST(RD.SurdNome AS VARCHAR(250)) AS REDE_DISTRIBUICAO,
        CAST(TF.SutfNome AS VARCHAR(250)) AS REDE_DISTRIBUICAO_OLD
    FROM PROJECT_CP_CONTRATO C WITH (NOLOCK)
    CROSS APPLY (
        SELECT CAST([dbo].[Func_JOB_CALCULAR_HONORARIO](CAST(C.CctCodigo AS VARCHAR(10)), 'C') AS FLOAT) AS HonorarioCalc
    ) H
    LEFT JOIN SMART_UNIDADES UCom WITH (NOLOCK) ON UCom.UniCodigo = ISNULL(C.CctUnidadeFranqCom, ISNULL(C.CctUnidadeFranqOp, 2153))
    LEFT JOIN SMART_PARTICIPANTES PCli WITH (NOLOCK) ON PCli.ParCodigo = C.CctCliente
    LEFT JOIN SMART_PARTICIPANTES PFranq WITH (NOLOCK) ON PFranq.ParCodigo = C.CctCliente
    OUTER APPLY (
        SELECT TOP 1 ModRedeDistribuicao, ModTipoFranquia 
        FROM SMART_UNIDADES_MODELOS WITH (NOLOCK)
        WHERE ModUnidade = ISNULL(C.CctUnidadeFranqCom, ISNULL(C.CctUnidadeFranqOp, 2153))
        ORDER BY ModAtivo DESC, ModData DESC
    ) M
    LEFT JOIN SMART_UNIDADES_REDE_DISTRIBUICAO RD WITH (NOLOCK) ON RD.SurdCodigo = M.ModRedeDistribuicao
    LEFT JOIN SMART_UNIDADES_TIPO_FRANQUIA TF WITH (NOLOCK) ON TF.SutfCodigo = M.ModTipoFranquia
    WHERE C.CctCodigo IS NOT NULL
)
SELECT
    JOB,
    PERC_HONORARIOS_JOB,
    PERC_HONORARIOS_FRANQUEADO,
    UNIDADE_ID,
    UNIDADE_EMAIL,
    CNPJ_UNIDADE,
    TIPO_FRANQUIA_CODIGO,
    TIPO_FRANQUIA_NOME,
    PARTICIPANTE_ID,
    PARTICIPANTE_RAZAO_SOCIAL,
    PARTICIPANTE_CONTATO_NOME,
    PERC_FRANQUEADO,
    DATA_CADASTRO,
    PARTICIPANTE_CPF,
    UNIDADE_NOME,
    COBRANCA_GROSSUP,
    CODIGO,
    RETENCAO,
    UNIRETEMIMPOSTO,
    PARTICIPANTE_CLIENTE,
    PARTICIPANTE_FRANQUEADO,
    REDE_DISTRIBUICAO,
    REDE_DISTRIBUICAO_OLD
FROM (
    SELECT * FROM Qbert
    UNION ALL
    SELECT * FROM CP
) X
"@

$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()
$cmd = $conn.CreateCommand()
$cmd.CommandTimeout = 120
$cmd.CommandText = $alterSql
$cmd.ExecuteNonQuery() | Out-Null
$conn.Close()
Write-Host "View vw_powerbi_job_repasse successfully updated on SQL Server!"
