version: "3.8"

services:
  automation:
    build: .
    container_name: studio_automation_core
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - TZ=America/Sao_Paulo
      - PYTHONPATH=/app