$connStr = "Server=192.168.2.34;Database=STUDIO_FISCAL;Integrated Security=True;TrustServerCertificate=True;"
$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()

$sql = @"
SELECT TOP 5
    A.JOB,
    CAST(A.PERCENTUAL AS FLOAT) AS PERC_HONORARIOS_JOB,
    CAST(A.PERCENTUAL AS FLOAT) AS PERC_HONORARIOS_FRANQUEADO,
    CAST(A.CODIGO_UNIDADE AS BIGINT) AS UNIDADE_ID,
    U.UniEmail AS UNIDADE_EMAIL,
    CAST('' AS VARCHAR(50)) AS CNPJ_UNIDADE,
    CAST(0 AS BIGINT) AS TIPO_FRANQUIA_CODIGO,
    CAST(TF.SutfNome AS VARCHAR(100)) AS TIPO_FRANQUIA_NOME,
    CAST(A.CODIGO_CLIENTE AS BIGINT) AS PARTICIPANTE_ID,
    CAST(PCli.ParRazao AS VARCHAR(250)) AS PARTICIPANTE_RAZAO_SOCIAL,
    CAST(PCli.ParContatoNome AS VARCHAR(250)) AS PARTICIPANTE_CONTATO_NOME,
    CAST(A.PERCENTUAL AS FLOAT) AS PERC_FRANQUEADO,
    A.DATA_CADASTRO,
    CAST(PCli.ParCNPJ AS VARCHAR(50)) AS PARTICIPANTE_CPF,
    CAST(U.UniNome AS VARCHAR(250)) AS UNIDADE_NOME,
    CASE WHEN A.COBRANCA_GROSSUP = 1 THEN 'N' ELSE 'S' END AS COBRANCA_GROSSUP,
    CAST(A.CODIGO AS BIGINT) AS CODIGO,
    CASE
        WHEN ISNULL(U.UniRetemImposto, 0) = 1 THEN CAST(0.00 AS FLOAT)
        WHEN A.COBRANCA_GROSSUP = 1 AND A.DATA_CADASTRO > '20260301' THEN CAST(19.53 AS FLOAT)
        ELSE CAST(0.00 AS FLOAT)
    END AS RETENCAO,
    CASE WHEN U.UniRetemImposto = 1 THEN 'N' ELSE 'S' END AS UNIRETEMIMPOSTO,
    CAST(PCli.ParRazao AS VARCHAR(250)) AS PARTICIPANTE_CLIENTE,
    CAST(PFranq.ParRazao AS VARCHAR(250)) AS PARTICIPANTE_FRANQUEADO,
    CAST(RD.SurdNome AS VARCHAR(250)) AS REDE_DISTRIBUICAO,
    CAST(TF.SutfNome AS VARCHAR(250)) AS REDE_DISTRIBUICAO_OLD
FROM PROJECT_QBERT_JOBS A WITH (NOLOCK)
LEFT JOIN SMART_UNIDADES U WITH (NOLOCK) ON U.UniCodigo = A.CODIGO_UNIDADE
LEFT JOIN SMART_PARTICIPANTES PCli WITH (NOLOCK) ON PCli.ParCodigo = A.CODIGO_CLIENTE
LEFT JOIN SMART_PARTICIPANTES PFranq WITH (NOLOCK) ON PFranq.ParCodigo = A.CODIGO_FRANQUEADO
LEFT JOIN SMART_UNIDADES_MODELOS M WITH (NOLOCK) ON M.ModUnidade = A.CODIGO_UNIDADE AND M.ModAtivo = 1
LEFT JOIN SMART_UNIDADES_REDE_DISTRIBUICAO RD WITH (NOLOCK) ON RD.SurdCodigo = M.ModRedeDistribuicao
LEFT JOIN SMART_UNIDADES_TIPO_FRANQUIA TF WITH (NOLOCK) ON TF.SutfCodigo = M.ModTipoFranquia
WHERE A.JOB LIKE '%75902%'
"@

$cmd = $conn.CreateCommand()
$cmd.CommandText = $sql
$r = $cmd.ExecuteReader()
while ($r.Read()) {
    Write-Output "=== Found Row ==="
    for ($i=0; $i -lt $r.FieldCount; $i++) {
        Write-Output ($r.GetName($i) + ': ' + $r.GetValue($i))
    }
}
$r.Close()
$conn.Close()
