$connStr = "Server=192.168.2.34;Database=STUDIO_FISCAL;Integrated Security=True;TrustServerCertificate=True;"
$query = @"
SELECT
	A.JOB,
	A.CODIGO,
	A.PERCENTUAL AS PERC_HONORARIOS_JOB,
	A.DATA_CADASTRO,
	ISNULL(U.PERC_FRANQUEADO, A.PERCENTUAL) AS PERC_HONORARIOS_FRANQUEADO,
    ISNULL(U.UNIDADE_ID, ISNULL(A.CODIGO_UNIDADE, 2153)) AS UNIDADE_ID,  
	ISNULL(U.UNIDADE_NOME, ISNULL(UDirect.UniNome, 'STUDIO CONTABILIDADE LTDA - PILOTO')) AS UNIDADE_NOME,
    U.UNIDADE_EMAIL AS UNIDADE_EMAIL,
    U.PARTICIPANTE_CPF AS CNPJ_UNIDADE,   
    U.TIPO_FRANQUIA_CODIGO,          
    U.TIPO_FRANQUIA_NOME,         
    U.PARTICIPANTE_ID,          
    U.PARTICIPANTE_RAZAO_SOCIAL,    
	U.PARTICIPANTE_CPF,
    U.PARTICIPANTE_CONTATO_NOME,          
    ISNULL(U.PERC_FRANQUEADO, A.PERCENTUAL) AS PERC_FRANQUEADO,
	CASE A.COBRANCA_GROSSUP WHEN 1 THEN 'N' ELSE 'S' END AS COBRANCA_GROSSUP,
	CASE 
		WHEN ISNULL(U.UNIRETEMIMPOSTO, 0) = 1 THEN 0
		WHEN A.COBRANCA_GROSSUP = 1 
			 AND A.DATA_CADASTRO > '20260301'
		THEN 19.53
		ELSE 0
	END AS RETENCAO,
    CASE ISNULL(U.UNIRETEMIMPOSTO, 0) WHEN 1 THEN 'N' ELSE 'S' END AS UNIRETEMIMPOSTO
FROM PROJECT_QBERT_JOBS AS A WITH (NOLOCK)
LEFT JOIN SMART_UNIDADES UDirect WITH (NOLOCK) ON UDirect.UniCodigo = A.CODIGO_UNIDADE
OUTER APPLY (
    SELECT TOP 1 *
    FROM vw_powerbi_participantes_unidades PU WITH (NOLOCK)
    WHERE PU.UNIDADE_ID = A.CODIGO_UNIDADE OR PU.PARTICIPANTE_ID = A.CODIGO_CLIENTE
    ORDER BY PU.ModAtivo DESC
) U
WHERE A.JOB IN ('83743', '83744', '83745', '86092-T')
"@
$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
$conn.Open()
$cmd = $conn.CreateCommand()
$cmd.CommandText = $query
$adapter = New-Object System.Data.SqlClient.SqlDataAdapter($cmd)
$dt = New-Object System.Data.DataTable
$adapter.Fill($dt) | Out-Null
$conn.Close()
$dt | Format-Table -AutoSize
